services:
  - type: web
    name: ytmp3-app
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 3"
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
